# Generated by Django 3.0.2 on 2020-05-06 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('babyteach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('words', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=200)),
                ('addtime', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 5, 49, 58, 997454, tzinfo=utc))),
            ],
        ),
    ]
