# Generated by Django 3.0.2 on 2020-05-07 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('babyteach', '0005_auto_20200507_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='pic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 5, 2, 58, 818642, tzinfo=utc)),
        ),
    ]
