# Generated by Django 3.0.2 on 2020-05-16 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyteach', '0006_auto_20200507_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 15, 32, 53, 527531)),
        ),
    ]
